import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { io } from "socket.io-client";
import { api, apiBaseUrl } from "./api";
import { remainingHoldSeconds } from "./bookingState";
import "./style.css";
type EventItem = { id: number; title: string; description: string; category: string; language: string; duration_minutes: number };
type Show = { id: number; event_title: string; starts_at: string; venue: { name: string; city: string }; auditorium: { name: string } };
type Seat = { show_seat_id: number; row_label: string; seat_number: number; price: string; status: "AVAILABLE" | "HELD" | "BOOKED" };
type Hold = { hold_id: string; total: string; expires_at: string };
type Booking = { booking_id: string; booking_reference: string; status: string; amount: string; show_id: number; items: { seat_label: string }[] };
type AuthResponse = { access_token: string; refresh_token: string; user: { email: string; full_name: string; role: string } };

declare global {
  interface Window {
    Razorpay?: new (options: Record<string, unknown>) => { open: () => void };
  }
}

const loadRazorpay = () => new Promise<void>((resolve, reject) => {
  if (window.Razorpay) { resolve(); return; }
  const script = document.createElement("script");
  script.src = "https://checkout.razorpay.com/v1/checkout.js";
  script.onload = () => resolve();
  script.onerror = () => reject(new Error("Could not load Razorpay Checkout."));
  document.body.appendChild(script);
});

const formatDate = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });

function App() {
  const [events, setEvents] = useState<EventItem[]>([]); const [cities, setCities] = useState<string[]>([]); const [city, setCity] = useState(""); const [event, setEvent] = useState<EventItem | null>(null);
  const [shows, setShows] = useState<Show[]>([]); const [showId, setShowId] = useState<number | null>(null);
  const [seats, setSeats] = useState<Seat[]>([]); const [selected, setSelected] = useState<number[]>([]);
  const [hold, setHold] = useState<Hold | null>(null); const [bookings, setBookings] = useState<Booking[]>([]);
  const [search, setSearch] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [fullName, setFullName] = useState(""); const [authMode, setAuthMode] = useState<"signin" | "register">("signin"); const [userName, setUserName] = useState("your account");
  const [message, setMessage] = useState("Browse an event to begin."); const [busy, setBusy] = useState(false); const [eventsLoading, setEventsLoading] = useState(true);
  const [showsLoading, setShowsLoading] = useState(false); const [showsError, setShowsError] = useState(""); const [seatsLoading, setSeatsLoading] = useState(false); const [seatsError, setSeatsError] = useState("");
  const [remainingSeconds, setRemainingSeconds] = useState<number | null>(null); const [loggedIn, setLoggedIn] = useState(Boolean(localStorage.getItem("access_token"))); const [userRole, setUserRole] = useState("");

  const loadEvents = async (query = search, selectedCity = city) => { setEventsLoading(true); try { setEvents((await api<{ items: EventItem[] }>(`/events?page=1&page_size=20&search=${encodeURIComponent(query)}&city=${encodeURIComponent(selectedCity)}`)).items); } catch (e) { setEvents([]); setMessage((e as Error).message); } finally { setEventsLoading(false); } };
  const loadCities = async () => { try { setCities((await api<{ items: string[] }>("/cities")).items); } catch { setCities([]); } };
  const loadSeats = async (id: number, preserveSelection = false) => { setSeatsLoading(true); setSeatsError(""); try { const items = (await api<{ items: Seat[] }>(`/shows/${id}/seats`)).items; setSeats(items); if (!hold && !preserveSelection) { setSelected((current) => { const available = new Set(items.filter((seat) => seat.status === "AVAILABLE").map((seat) => seat.show_seat_id)); const next = current.filter((seatId) => available.has(seatId)); if (next.length !== current.length) setMessage("Seat availability changed. Unavailable selections were removed."); return next; }); } } catch (e) { setSeats([]); setSeatsError((e as Error).message); } finally { setSeatsLoading(false); } };
  const loadBookings = async () => { if (!localStorage.getItem("access_token")) return; try { setBookings((await api<{ items: Booking[] }>("/bookings")).items); } catch (e) { setMessage((e as Error).message); } };
  const loadCurrentUser = async () => { if (!localStorage.getItem("access_token")) return; try { const result = await api<{ user: { full_name: string; role: string } }>("/users/me"); setUserName(result.user.full_name); setUserRole(result.user.role); } catch { setUserRole(""); } };

  useEffect(() => { const handleExpired = () => { setLoggedIn(false); setUserRole(""); setBookings([]); setHold(null); setSelected([]); setMessage("Your session expired. Please sign in again before holding seats."); }; window.addEventListener("auth:expired", handleExpired); void loadEvents(""); void loadCities(); void loadBookings(); void loadCurrentUser(); return () => window.removeEventListener("auth:expired", handleExpired); }, []);
  useEffect(() => { if (!hold) { setRemainingSeconds(null); return; } const update = () => { const seconds = remainingHoldSeconds(hold.expires_at); setRemainingSeconds(seconds); if (seconds === 0) { setHold(null); setSelected([]); setMessage("Your hold expired. The seat map was reloaded."); if (showId !== null) void loadSeats(showId); } }; update(); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer); }, [hold, showId]);
  useEffect(() => { if (showId === null) return; void loadSeats(showId); const socket = io(import.meta.env.VITE_SOCKET_URL ?? "http://localhost:5000", { reconnection: true, transports: ["polling"] }); socket.on("connect", () => socket.emit("join_show", showId)); socket.on("SEAT_STATUS_CHANGED", () => void loadSeats(showId)); return () => { socket.emit("leave_show", showId); socket.close(); }; }, [showId]);

  const authenticate = async (register: boolean) => { setBusy(true); try { const result = await api<AuthResponse>(register ? "/auth/register" : "/auth/login", { method: "POST", body: JSON.stringify(register ? { email, password, full_name: fullName } : { email, password }) }); localStorage.setItem("access_token", result.access_token); localStorage.setItem("refresh_token", result.refresh_token); setUserName(result.user.full_name); setUserRole(result.user.role); setLoggedIn(true); setMessage(register ? "Account created successfully. You are now signed in." : `Welcome back, ${result.user.full_name}.`); await loadBookings(); } catch (e) { setMessage(`${register ? "Account creation failed" : "Sign-in failed"}: ${(e as Error).message}`); } finally { setBusy(false); } };
  const selectEvent = async (item: EventItem) => { setBusy(true); setEvent(item); setShowId(null); setSelected([]); setHold(null); setShows([]); setShowsError(""); setShowsLoading(true); try { setShows((await api<{ items: Show[] }>(`/events/${item.id}/shows`)).items); setMessage("Choose a showtime."); } catch (e) { setShowsError((e as Error).message); setMessage("We could not load showtimes."); } finally { setShowsLoading(false); setBusy(false); } };
  const selectShow = (id: number) => { setShowId(id); setSelected([]); setHold(null); setMessage("Select available seats. The server confirms the final hold."); };
  const createHold = async () => { if (showId === null || !selected.length) return; setBusy(true); try { const result = await api<Hold>(`/shows/${showId}/holds`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ show_seat_ids: selected }) }); setHold(result); setMessage(`Seats held successfully until ${formatDate(result.expires_at)}.`); await loadSeats(showId, true); } catch (e) { setSelected([]); setMessage(`Could not hold those seats: ${(e as Error).message} Please choose the seats marked Available and try again.`); await loadSeats(showId); } finally { setBusy(false); } };
  const checkout = async () => { if (!hold) return; setBusy(true); try { const booking = await api<Booking>("/bookings", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ hold_id: hold.hold_id }) }); const payment = await api<{ payment_id: string; provider: string; provider_order_id?: string; razorpay_key_id?: string; amount: string; currency: string }>("/payments", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ booking_id: booking.booking_id }) }); if (payment.provider === "RAZORPAY") { await loadRazorpay(); await new Promise<void>((resolve, reject) => { if (!window.Razorpay) { reject(new Error("Razorpay Checkout is unavailable.")); return; } const razorpayCheckout = new window.Razorpay({ key: payment.razorpay_key_id, amount: Math.round(Number(payment.amount) * 100), currency: payment.currency, name: "Ticket Booking System", description: "Ticket booking", order_id: payment.provider_order_id, handler: async (response: Record<string, string>) => { try { await api(`/payments/${payment.payment_id}/verify`, { method: "POST", body: JSON.stringify(response) }); resolve(); } catch (error) { reject(error); } }, modal: { ondismiss: () => reject(new Error("Payment window was closed. Your seats remain held until the timer expires.")) } }); razorpayCheckout.open(); }); } else { await api(`/payments/${payment.payment_id}/simulate`, { method: "POST", body: JSON.stringify({ outcome: "SUCCESS" }) }); } setMessage(`Booking ${booking.booking_reference} confirmed.`); setHold(null); setSelected([]); await loadSeats(showId!); await loadBookings(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } };
  const cancelBooking = async (bookingId: string) => { setBusy(true); try { await api(`/bookings/${bookingId}/cancel`, { method: "POST" }); setMessage("Booking cancelled and seats released."); await loadBookings(); if (showId) await loadSeats(showId); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }; const logout = () => { localStorage.removeItem("access_token"); localStorage.removeItem("refresh_token"); setLoggedIn(false); setBookings([]); setHold(null); setSelected([]); setUserName("your account"); setUserRole(""); setMessage("You are signed out. Browse events or sign in to book seats."); };
  const currentShow = shows.find((show) => show.id === showId);

  return <main className="app-shell">
    <header className="topbar"><div><p className="eyebrow">TICKET BOOKING SYSTEM</p><h1>Your next great night starts here.</h1><p className="hero-copy">Discover live events, choose your perfect seats, and check out in seconds.</p></div><div className="top-actions">{loggedIn ? <div className="signed-in"><span className="account-badge">Signed in</span><span>{userName}</span><button className="ghost" onClick={logout}>Sign out</button></div> : <span className="account-badge">Browsing as guest</span>}</div></header>
    <div className={`notification ${/failed|incorrect|could not|error|unavailable|expired|requires|invalid/i.test(message) ? "notification-error" : ""}`} role="status"><span className="notification-dot" />{message}</div>
    <section className="learning-strip"><span>Booking flow</span><strong>1. Browse</strong><span>→</span><strong>2. Choose seats</strong><span>→</span><strong>3. Hold</strong><span>→</span><strong>4. Pay securely</strong></section>
    <section className="catalogue-section"><div className="section-heading"><div><p className="eyebrow">EXPLORE</p><h2>Events and shows</h2></div><div className="search"><select aria-label="Filter by city" value={city} onChange={(e) => { setCity(e.target.value); void loadEvents(search, e.target.value); }}><option value="">All cities</option>{cities.map((item) => <option key={item} value={item}>{item}</option>)}</select><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") void loadEvents(search, city); }} placeholder="Search events" /><button onClick={() => void loadEvents(search, city)}>Search</button></div></div>
      {eventsLoading ? <p className="inline-status">Loading events…</p> : events.length ? <div className="event-grid">{events.map((item) => <button className={`event-card ${event?.id === item.id ? "active" : ""}`} key={item.id} onClick={() => void selectEvent(item)}><span className="event-art"><span>{item.title.split(" ").slice(0, 2).map((word) => word[0]).join("")}</span><small>{item.category}</small></span><span className="event-category">{item.category}</span><h3>{item.title}</h3><p>{item.description}</p><small className="event-meta">{item.language} · {item.duration_minutes} min</small></button>)}</div> : <p className="empty-state">No active events found. Try another search.</p>}
      {event && <div className="show-panel"><div><p className="eyebrow">{event.title}</p><h3>Select a showtime</h3><p className="muted">Choose a date and venue to see the live seat map.</p></div><div className="show-list">{showsLoading ? <p className="inline-status">Loading showtimes…</p> : showsError ? <p className="error-state">{showsError} <button className="text-button" onClick={() => void selectEvent(event)}>Retry</button></p> : shows.length ? shows.map((show) => <button className={showId === show.id ? "show-option selected-show" : "show-option"} key={show.id} onClick={() => selectShow(show.id)}><strong>{formatDate(show.starts_at)}</strong><span>{show.venue.name}, {show.venue.city} · {show.auditorium.name}</span></button>) : <p className="empty-state">No upcoming showtimes for this event.</p>}</div></div>}
    </section>
    {showId !== null && <section className="booking-layout"><div className="seat-card"><div className="section-heading"><div><p className="eyebrow">{currentShow?.venue.city}</p><h2>Choose your seats</h2></div><span className="legend"><i className="dot available" /> Available <i className="dot held" /> Held <i className="dot booked" /> Booked</span></div><div className="screen">SCREEN</div>{seatsLoading ? <div className="seat-placeholder">Loading the live seat map…</div> : seatsError ? <div className="seat-placeholder error-state">{seatsError}<button className="text-button" onClick={() => void loadSeats(showId)}>Retry</button></div> : seats.length ? <div className="seat-grid">{seats.map((seat) => <button key={seat.show_seat_id} aria-label={`${seat.row_label}${seat.seat_number} ${seat.status}`} className={`seat ${seat.status.toLowerCase()} ${selected.includes(seat.show_seat_id) ? "selected" : ""}`} disabled={seat.status !== "AVAILABLE" || Boolean(hold)} onClick={() => setSelected((current) => current.includes(seat.show_seat_id) ? current.filter((id) => id !== seat.show_seat_id) : current.length < 10 ? [...current, seat.show_seat_id] : current)}>{seat.row_label}{seat.seat_number}</button>)}</div> : <div className="seat-placeholder">No seats are configured for this show.</div>}<p className="seat-help">{seats.length ? `${selected.length}/10 selected · Maximum ten seats per hold` : "Select a showtime to load seats."}</p></div><aside className="checkout-card"><p className="eyebrow">YOUR ORDER</p><h2>{selected.length ? `${selected.length} seat${selected.length > 1 ? "s" : ""}` : "No seats yet"}</h2><p className="muted">Your seats are reserved only after the server confirms the hold.</p>{hold ? <><div className="price-row"><span>Held total</span><strong>₹{hold.total}</strong></div><p className="hold-warning">Expires in <strong>{remainingSeconds === null ? "…" : `${Math.floor(remainingSeconds / 60)}:${String(remainingSeconds % 60).padStart(2, "0")}`}</strong></p><button disabled={busy} onClick={() => void checkout()}>{busy ? "Confirming…" : "Pay and confirm"}</button></> : <button disabled={!selected.length || busy || seatsLoading} onClick={() => void createHold()}>{busy ? "Holding…" : "Hold selected seats"}</button>}</aside></section>}
    {!loggedIn ? <section className="auth-card"><div><p className="eyebrow">ACCOUNT</p><h2>{authMode === "signin" ? "Welcome back." : "Create your account."}</h2><p className="muted">{authMode === "signin" ? "Sign in to hold seats and view your bookings." : "Create a local learning account to reserve seats and view booking history."}</p><div className="auth-switch"><button className={authMode === "signin" ? "switch-active" : "ghost"} onClick={() => setAuthMode("signin")}>Sign in</button><button className={authMode === "register" ? "switch-active" : "ghost"} onClick={() => setAuthMode("register")}>Create account</button></div></div>{authMode === "register" && <input placeholder="Full name" value={fullName} onChange={(e) => setFullName(e.target.value)} />}{authMode === "signin" && <div className="form-hint">Already have a learning account? Sign in below.</div>}<input placeholder="Email address" value={email} onChange={(e) => setEmail(e.target.value)} /><input placeholder="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="primary-auth" disabled={busy} onClick={() => void authenticate(authMode === "register")}>{busy ? "Please wait…" : authMode === "signin" ? "Sign in" : "Create account"}</button></section> : <section className="history-card"><div className="section-heading"><div><p className="eyebrow">ACCOUNT</p><h2>Your bookings</h2></div><button className="ghost" disabled={busy} onClick={() => void loadBookings()}>Refresh</button></div>{bookings.length ? bookings.map((booking) => <div className="booking-row" key={booking.booking_id}><div><strong>{booking.booking_reference}</strong><span>{booking.items.map((item) => item.seat_label).join(", ")} · ₹{booking.amount}</span></div><div><span className={`status-pill ${booking.status.toLowerCase()}`}>{booking.status}</span>{booking.status === "CONFIRMED" && <button className="text-button" disabled={busy} onClick={() => void cancelBooking(booking.booking_id)}>Cancel</button>}</div></div>) : <p className="empty-state">No bookings yet. Choose a show above.</p>}</section>}
    {userRole === "ADMIN" && <AdminPanel onMessage={setMessage} />}
    <footer>API readiness: <a href={`${apiBaseUrl.replace(/\/api\/v1\/?$/, "")}/health/ready`}>check dependencies</a></footer>
  </main>;
}

function AdminPanel({ onMessage }: { onMessage: (message: string) => void }) {
  const [eventTitle, setEventTitle] = useState(""); const [eventCategory, setEventCategory] = useState("MOVIE"); const [eventLanguage, setEventLanguage] = useState("English"); const [eventDescription, setEventDescription] = useState("");
  const [venueName, setVenueName] = useState(""); const [venueCity, setVenueCity] = useState(""); const [venueAddress, setVenueAddress] = useState("");
  const [venueId, setVenueId] = useState(""); const [auditoriumName, setAuditoriumName] = useState("Screen 1"); const [rows, setRows] = useState("A,B,C,D,E,F"); const [seatsPerRow, setSeatsPerRow] = useState("10");
  const [eventId, setEventId] = useState(""); const [auditoriumId, setAuditoriumId] = useState(""); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [price, setPrice] = useState("250.00"); const [adminBusy, setAdminBusy] = useState(false);
  const submit = async (path: string, body: unknown, success: string) => { setAdminBusy(true); try { await api(path, { method: "POST", body: JSON.stringify(body) }); onMessage(success); } catch (e) { onMessage(`Admin action failed: ${(e as Error).message}`); } finally { setAdminBusy(false); } };
  return <section className="admin-card"><div className="admin-heading"><div><p className="eyebrow">ADMIN WORKSPACE</p><h2>Manage catalogue</h2><p className="muted">Create catalogue records through protected APIs. IDs returned after each step connect the records together.</p></div><span className="admin-badge">ADMIN ONLY</span></div><div className="admin-grid">
    <form onSubmit={(e) => { e.preventDefault(); void submit("/admin/events", { title: eventTitle, category: eventCategory, language: eventLanguage, description: eventDescription, duration_minutes: 120 }, "Event created. Save its returned ID for scheduling."); }}><h3>1. Add event</h3><input required placeholder="Event title" value={eventTitle} onChange={(e) => setEventTitle(e.target.value)} /><input placeholder="Category e.g. MOVIE" value={eventCategory} onChange={(e) => setEventCategory(e.target.value)} /><input placeholder="Language" value={eventLanguage} onChange={(e) => setEventLanguage(e.target.value)} /><textarea placeholder="Description" value={eventDescription} onChange={(e) => setEventDescription(e.target.value)} /><button disabled={adminBusy}>Create event</button></form>
    <form onSubmit={(e) => { e.preventDefault(); void submit("/admin/venues", { name: venueName, city: venueCity, address: venueAddress, timezone: "Asia/Kolkata" }, "Venue created. Save its ID for the auditorium."); }}><h3>2. Add location</h3><input required placeholder="Venue name" value={venueName} onChange={(e) => setVenueName(e.target.value)} /><input required placeholder="City" value={venueCity} onChange={(e) => setVenueCity(e.target.value)} /><input required placeholder="Address" value={venueAddress} onChange={(e) => setVenueAddress(e.target.value)} /><button disabled={adminBusy}>Create venue</button></form>
    <form onSubmit={(e) => { e.preventDefault(); void submit("/admin/auditoriums", { venue_id: Number(venueId), name: auditoriumName, row_labels: rows.split(",").map((row) => row.trim()).filter(Boolean), seats_per_row: Number(seatsPerRow) }, "Auditorium and physical seats created. Save its ID for the show."); }}><h3>3. Add screen and seats</h3><input required type="number" placeholder="Venue ID" value={venueId} onChange={(e) => setVenueId(e.target.value)} /><input required placeholder="Screen name" value={auditoriumName} onChange={(e) => setAuditoriumName(e.target.value)} /><input required placeholder="Rows: A,B,C" value={rows} onChange={(e) => setRows(e.target.value)} /><input required type="number" placeholder="Seats per row" value={seatsPerRow} onChange={(e) => setSeatsPerRow(e.target.value)} /><button disabled={adminBusy}>Create screen</button></form>
    <form onSubmit={(e) => { e.preventDefault(); void submit("/admin/shows", { event_id: Number(eventId), auditorium_id: Number(auditoriumId), starts_at: new Date(startsAt).toISOString(), ends_at: new Date(endsAt).toISOString(), booking_opens_at: new Date().toISOString(), booking_closes_at: new Date(endsAt).toISOString(), price }, "Show scheduled and show-seat inventory materialized."); }}><h3>4. Schedule show</h3><input required type="number" placeholder="Event ID" value={eventId} onChange={(e) => setEventId(e.target.value)} /><input required type="number" placeholder="Auditorium ID" value={auditoriumId} onChange={(e) => setAuditoriumId(e.target.value)} /><label>Starts<input required type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} /></label><label>Ends<input required type="datetime-local" value={endsAt} onChange={(e) => setEndsAt(e.target.value)} /></label><input required placeholder="Ticket price" value={price} onChange={(e) => setPrice(e.target.value)} /><button disabled={adminBusy}>Schedule show</button></form>
  </div></section>;
}

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
